FROM centos:latest
#RUN yum update -y
#RUN yum upgrade -y


RUN yum install gcc tar openssl-devel bzip2-devel libffi-devel

MAINTAINER Valentin Vulea "valentin.vulea@gmail.com"

#Download Python 3.7.3
RUN cd /usr/src
RUN wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz

#Unzip Archive
RUN tar xzf Python-3.7.3.tgz

#Install Python
RUN cd Python-3.7.3
RUN ./configure --enable-optimizations
RUN make altinstall


#Removes Archive for Installation
RUN rm /usr/src/Python-3.7.3.tgz

RUN python3.7 -V


#Test din GitHub
#Test Git Repo Update
